# Generated by Django 3.2.6 on 2021-08-15 10:49

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('from_currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('USD', 'United States Dollar')], default='BTC', max_length=4)),
                ('to_currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('USD', 'United States Dollar')], default='USD', max_length=4)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=12)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=12)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
