# Generated by Django 3.2.6 on 2021-08-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='ask_price',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='bid_price',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
    ]
