version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A btc_exchange worker -l debug
    volumes:
      - .:/code
    env_file:
      - web-variables.env
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A btc_exchange beat -l debug
    volumes:
      - .:/code
    env_file:
      - web-variables.env
    depends_on:
      - redis
  web:
    build: .
    command: './start.sh'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - web-variables.env
    depends_on:
      - db
      - redis


volumes:
  pgdata:
